FROM php:8.3.12-fpm

# Instala dependências
RUN apt-get update && apt-get install -y \
    cron \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copia o código da aplicação
COPY app /var/www

# Define o diretório de trabalho
WORKDIR /var/www

COPY cronjob /etc/cron.d/laravel-schedule

# Dá permissão ao cronjob
RUN chmod 0644 /etc/cron.d/laravel-schedule

# Aplica o cronjob
RUN crontab /etc/cron.d/laravel-schedule

# Exponha a porta
EXPOSE 9000

# Comando para iniciar o PHP-FPM e o cron em segundo plano
CMD ["sh", "-c", "cron && php-fpm"]
